# Confusion Matrix Implementation - Iris Dataset

1.Uses inbuilt logistic Regression and Iris Datasets
2.Prints the number of wrong predictions
3.Prints the Probabilites of Exactly how much each row belongs to a particular class
4.Prints the Confusion Matrix

In [31]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn import model_selection
from sklearn.metrics import confusion_matrix

In [8]:
#Loading Iris Dataset
iris = datasets.load_iris()
x = iris.data
y = iris.target

In [10]:
#Splitting data into train and Test
x_train, x_test, y_train, y_test = model_selection.train_test_split(x,y)
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(112, 4) (112,)
(38, 4) (38,)


In [17]:
clf = LogisticRegression(multi_class ='auto' ,solver = 'liblinear')

In [18]:
clf.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='auto',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [21]:
y_pred_train = clf.predict(x_train)
y_pred_test = clf.predict(x_test)

array([1, 1, 1, 2, 2, 1, 1, 0, 0, 0, 2, 2, 0, 0, 1, 2, 0, 1, 2, 2, 0, 2,
       2, 0, 1, 2, 1, 1, 1, 0, 2, 1, 0, 0, 0, 2, 2, 1, 2, 2, 1, 2, 0, 2,
       0, 2, 1, 0, 1, 1, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 1, 2, 0, 2, 2, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 2, 2, 1, 2, 0, 2, 1, 1, 2, 2, 0, 2, 2, 1,
       1, 1, 2, 0, 0, 1, 0, 1, 2, 2, 1, 0, 0, 2, 1, 0, 2, 1, 0, 2, 0, 1,
       0, 1])

In [22]:
#Number of Wrong Predictions
print( (y_pred_train - y_train).sum() )
print( (y_pred_test - y_test).sum() )


4
1


In [32]:
#Probability of classes
clf.predict_proba(iris.data)

array([[8.66179342e-01, 1.33790876e-01, 2.97816524e-05],
       [7.88272236e-01, 2.11652146e-01, 7.56186741e-05],
       [8.41625589e-01, 1.58308477e-01, 6.59340980e-05],
       [8.18077301e-01, 1.81780498e-01, 1.42201616e-04],
       [8.85075132e-01, 1.14893724e-01, 3.11440724e-05],
       [9.13085125e-01, 8.68797840e-02, 3.50905600e-05],
       [8.82833496e-01, 1.17069348e-01, 9.71557975e-05],
       [8.50636455e-01, 1.49313106e-01, 5.04397293e-05],
       [7.96331300e-01, 2.03469479e-01, 1.99221561e-04],
       [7.90037495e-01, 2.09894584e-01, 6.79207231e-05],
       [8.78226200e-01, 1.21755865e-01, 1.79348283e-05],
       [8.55498736e-01, 1.44411528e-01, 8.97360764e-05],
       [7.82014013e-01, 2.17914764e-01, 7.12221179e-05],
       [8.26481994e-01, 1.73436718e-01, 8.12872123e-05],
       [9.10414840e-01, 8.95820220e-02, 3.13817297e-06],
       [9.53047916e-01, 4.69450995e-02, 6.98410608e-06],
       [9.24242814e-01, 7.57436677e-02, 1.35179465e-05],
       [8.75701611e-01, 1.24261

In [35]:
#Printing Confuion Matrix for Training data and Testing Data
print(confusion_matrix(y_pred_train, y_train))
print()
print(confusion_matrix(y_pred_test, y_test))

[[36  0  0]
 [ 0 34  0]
 [ 0  4 38]]

[[14  0  0]
 [ 0 11  0]
 [ 0  1 12]]
